-- ********** Version History  **************************************************************************
-- US13565_TA15149  - 2024-11-26 - Shaurya Rawat - Initial Build for CustomerInvoiceLineFact DDL Script

-- *******************************************************************************************************

-- Create Staging table for Customer Invoice Line Fact
CREATE TABLE IF NOT EXISTS stg.{p_table_name}
(
    Rec_Process_Log_Id STRING,
    Rec_Src_Application_Id INT,
    Rec_Src_Key STRING,
    Cus_Trans_Num STRING,
    Cus_Trans_Ln_Num STRING,
    Rec_Src_Create_Date TIMESTAMP,
    Rec_Src_Create_User STRING,
    Rec_Src_Update_Date TIMESTAMP,
    Rec_Src_Update_User STRING,
    Rec_EDW_Hash STRING,
    Rec_EDW_Create_Date TIMESTAMP,
    Rec_EDW_Update_Date TIMESTAMP,
    Customer_Account_Dim_Id BIGINT,
    Product_Dim_Id BIGINT,
    Fiscal_Period_Dim_Id BIGINT,
    Legal_Entity_Dim_Id BIGINT,
    Covered_Product_Dim_Id BIGINT,
    Order_Dim_Id BIGINT,
    Order_Line_Dim_Id BIGINT,
    Quote_Dim_Id BIGINT,
    Quote_Line_Dim_Id BIGINT,
    Contract_Line_Dim_Id BIGINT,
    Transaction_Currency_Code STRING,
    Accounting_Currency_Code STRING,
    Reporting_Currency_Code STRING,
    Unit_of_Measure_Dim_Id BIGINT,
    Payment_Term_Dim_Id BIGINT,
    Payment_Specification_Dim_Id BIGINT,
    Payment_Method_Dim_Id BIGINT,
    Invoice_Payment_Status_Dim_Id BIGINT,
    Invoice_Status_Dim_Id BIGINT,
    Ledger_Transaction_Type_Dim_Id BIGINT,
    Invoice_Document_Date_Dim_Id BIGINT,
    Delivery_Address_Dim_Id BIGINT,
    Transaction_Date_Dim_Id BIGINT,
    Invoice_Due_Date_Dim_Id BIGINT,
    Document_Image_URL STRING,
    Voucher_Num STRING,
    Invoice_Num STRING,
    Invoice_Line_Num STRING,
    Invoice_Line_Desc STRING,
    PO_Num STRING,
    Src_Invoice_Num VARCHAR(1000),
    Project_Num VARCHAR(100),
    Journal_Num STRING,
    Invoice_Active_Ind TINYINT,
    Invoice_Posted_Ind TINYINT,
    Total_Invoice_Amt_TC DECIMAL(18, 5),
    Total_Invoice_Amt_USD DECIMAL(18, 5),
    Invoice_Ln_Qty DECIMAL(18, 4),
    Invoice_Ln_Amt_TC DECIMAL(18, 4),
    Invoice_Ln_Tax_Amt_TC DECIMAL(18, 4),
    Settlement_Amt_TC DECIMAL(18,4),
		ETL_Ins_Upd_Flag STRING  
  )USING DELTA LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Staging/{p_table_name}/{p_security_class}';


-- Create EDW table for Customer Invoice Line Fact
CREATE TABLE IF NOT EXISTS edw.{p_table_name}
(
    Customer_Invoice_Line_Fact_Id BIGINT GENERATED ALWAYS AS IDENTITY,
    Rec_Process_Log_Id BIGINT NOT NULL,
    Rec_Src_Application_Id INT,
    Rec_Src_Key STRING,
    Cus_Trans_Num STRING,
    Cus_Trans_Ln_Num STRING,
    Rec_Src_Create_Date TIMESTAMP NOT NULL,
    Rec_Src_Create_User STRING,
    Rec_Src_Update_Date TIMESTAMP NOT NULL,
    Rec_Src_Update_User STRING,
    Rec_EDW_Hash STRING,
    Rec_EDW_Create_Date TIMESTAMP,
    Rec_EDW_Update_Date TIMESTAMP,
    Customer_Account_Dim_Id BIGINT NOT NULL,
    Product_Dim_Id BIGINT NOT NULL,
    Fiscal_Period_Dim_Id BIGINT NOT NULL,
    Legal_Entity_Dim_Id BIGINT NOT NULL,
    Covered_Product_Dim_Id BIGINT NOT NULL,
    Order_Dim_Id BIGINT NOT NULL,
    Order_Line_Dim_Id BIGINT NOT NULL,
    Quote_Dim_Id BIGINT NOT NULL,
    Quote_Line_Dim_Id BIGINT NOT NULL,
    Contract_Line_Dim_Id BIGINT NOT NULL,
    Transaction_Currency_Code STRING,
    Accounting_Currency_Code STRING,
    Reporting_Currency_Code STRING,
    Unit_of_Measure_Dim_Id BIGINT NOT NULL,
    Payment_Term_Dim_Id BIGINT NOT NULL,
    Payment_Specification_Dim_Id BIGINT NOT NULL,
    Payment_Method_Dim_Id BIGINT NOT NULL,
    Invoice_Payment_Status_Dim_Id BIGINT NOT NULL,
    Invoice_Status_Dim_Id BIGINT NOT NULL,
    Ledger_Transaction_Type_Dim_Id BIGINT NOT NULL,
    Invoice_Document_Date_Dim_Id BIGINT NOT NULL,
    Delivery_Address_Dim_Id BIGINT NOT NULL,
    Transaction_Date_Dim_Id BIGINT NOT NULL,
    Invoice_Due_Date_Dim_Id BIGINT NOT NULL,
    Document_Image_URL STRING,
    Voucher_Num STRING,
    Invoice_Num STRING,
    Invoice_Line_Num STRING,
    Invoice_Line_Desc STRING,
    PO_Num STRING,
    Src_Invoice_Num VARCHAR(1000),
    Project_Num VARCHAR(100),
    Journal_Num STRING,
    Invoice_Active_Ind TINYINT NOT NULL,
    Invoice_Posted_Ind TINYINT NOT NULL,
    Total_Invoice_Amt_TC DECIMAL(18, 5),
    Total_Invoice_Amt_USD DECIMAL(18, 5),
    Invoice_Ln_Qty DECIMAL(18, 4) NOT NULL,
    Invoice_Ln_Amt_TC DECIMAL(18, 4),
    Invoice_Ln_Tax_Amt_TC DECIMAL(18, 4),
    Settlement_Amt_TC DECIMAL(18,4)
  )USING DELTA LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/EDW/{p_table_name}/{p_security_class}';
    

