-- *****
-- date_dim : This table is one time load into EDW
-- Created By: Shaurya Rawat
-- *****


-- Create EDW schema table
CREATE TABLE IF NOT EXISTS edw.date_dim (
  Date_Dim_Id INT,
  Calendar_Name STRING,
  Date_Num INT,
  Calendar_Date DATE,
  Date_Long_Name STRING,
  Weekday_Name STRING,
  Weekday_Name_Abrv STRING,
  Weekday_Num INT,
  Day_of_Month INT,
  Day_of_Quarter INT,
  Day_of_Year INT,
  Week_Num INT,
  Week_Long_Name STRING,
  Week_Start_Date DATE,
  Week_End_Date DATE,
  Month_Dim_Id INT,
  Month_Num INT,
  Month_Name STRING,
  Month_Name_Abrv STRING,
  Month_Year_Desc STRING,
  Month_Year_Long_Desc STRING,
  Month_Period_Desc STRING,
  Month_of_Quarter INT,
  Month_Start_Date DATE,
  Month_End_Date DATE,
  Quarter_Num INT,
  Quarter_Name STRING,
  Quarter_Long_Name STRING,
  Quarter_Name_Abrv STRING,
  Quarter_Period_Desc STRING,
  Quarter_Start_Date DATE,
  Quarter_End_Date DATE,
  Year_Num INT,
  Year_Period_Desc STRING,
  Year_Start_Date DATE,
  Year_End_Date DATE,
  Prior_Date DATE,
  Prior_Month_Num INT,
  Prior_Month_Name STRING,
  Prior_Month_Name_Abrv STRING,
  Prior_Month_Year_Desc STRING,
  Prior_Month_Period_Desc STRING,
  Prior_Month_Quarter_Num INT,
  Prior_Month_Year_Num INT,
  Prior_Month_Start_Date DATE,
  Prior_Month_End_Date DATE,
  Prior_Quarter_Num INT,
  Prior_Quarter_Name STRING,
  Prior_Quarter_Long_Name STRING,
  Prior_Quarter_Name_Abrv STRING,
  Prior_Quarter_Year_Num INT,
  Prior_Quarter_Start_Date DATE,
  Prior_Quarter_End_Date DATE,
  Prior_Year_Num INT,
  Prior_Year_Start_Date DATE,
  Prior_Year_End_Date DATE,
  Next_Date DATE,
  Next_Month_Num INT,
  Next_Month_Name STRING,
  Next_Month_Name_Abrv STRING,
  Next_Month_Year_Desc STRING,
  Next_Month_Period_Desc STRING,
  Next_Month_Quarter_Num INT,
  Next_Month_Year_Num INT,
  Next_Month_Start_Date DATE,
  Next_Month_End_Date DATE,
  Next_Quarter_Num INT,
  Next_Quarter_Name STRING,
  Next_Quarter_Long_Name STRING,
  Next_Quarter_Name_Abrv STRING,
  Next_Quarter_Year_Num INT,
  Next_Quarter_Start_Date DATE,
  Next_Quarter_End_Date DATE,
  Next_Year_Num INT,
  Next_Year_Start_Date DATE,
  Next_Year_End_Date DATE
)
USING DELTA 
LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/EDW/Date_Dim/Internal';

