-- ********** Version History  *******************************************************
-- US9858  - 2024-06-18 - Shaurya Rawat / Kerri - Change Dim to source from Salesforce and OEBS directly
-- US10250 - 2024-06-22 - KerriB - Added Prod_Line_Item_Cat
-- US11907 - 2024-09-24 - Shaurya Rawat - Added Prod_Legacy_Name

-- ***********************************************************************************

CREATE TABLE IF NOT EXISTS raw_salesforce_ukg.product2 
USING delta LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Raw/UKG/Salesforce/Product2/Internal';

CREATE TABLE IF NOT EXISTS raw_oebs_kronos.mtl_item_categories 
USING delta LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Raw/Kronos/OEBS/INV_MTL_ITEM_CATEGORIES/Internal';

CREATE TABLE IF NOT EXISTS raw_oebs_kronos.mtl_category_sets 
USING delta LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Raw/Kronos/OEBS/APPS_MTL_CATEGORY_SETS/Internal';

CREATE TABLE IF NOT EXISTS raw_oebs_kronos.mtl_categories_b 
USING delta LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Raw/Kronos/OEBS/INV_MTL_CATEGORIES_B/Internal';

CREATE TABLE IF NOT EXISTS raw_oebs_kronos.gl_code_combinations_kfv 
USING delta LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Raw/Kronos/OEBS/APPS_GL_CODE_COMBINATIONS_KFV/Internal';

CREATE TABLE IF NOT EXISTS raw_oebs_kronos.mtl_system_items_b 
USING delta LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Raw/Kronos/OEBS/ INV_MTL_SYSTEM_ITEMS_B/Internal';


CREATE TABLE IF NOT EXISTS stg.{p_table_name} 
(
	Rec_Process_Log_Id INT NOT NULL,
	Rec_Src_Application_Id INT NOT NULL,
	Rec_Src_Key STRING NOT NULL,
	Rec_Src_Create_Date TIMESTAMP,
	Rec_Src_Create_User STRING,
	Rec_Src_Update_Date TIMESTAMP,
	Rec_Src_Update_User STRING,
	Rec_EDW_Hash STRING,
	Rec_EDW_Create_Date TIMESTAMP NOT NULL,
	Rec_EDW_Update_Date TIMESTAMP NOT NULL,
	Rec_EDW_Effective_Start_Date TIMESTAMP NOT NULL,
	Rec_EDW_Effective_End_Date TIMESTAMP NOT NULL,
	Rec_EDW_Current_Ind INT NOT NULL,
	Prod_Name STRING,
	Prod_Legacy_Item_Num STRING,
	Prod_Legacy_Inventory_Item_Num STRING,
	Prod_Legacy_Org_Num STRING NOT NULL,
	Prod_Item_Num STRING, 
	Prod_Ext_ID STRING, 
	Prod_Cat STRING,
	Prod_Family STRING,
	Prod_Hosting_Component_Ind INT,
	Prod_PSA_Contract_Type STRING,
	Prod_Cus_Asset_Ind INT NOT NULL,
	Prod_Billing_Freq STRING,
	Prod_UOM STRING, 
	Prod_Active_Ind INT NOT NULL,
	Prod_Subinventory STRING,
	Prod_Solution STRING,
	Prod_Solution_Cat_1 STRING,
	Prod_Solution_Cat_2 STRING,
	Prod_Type STRING,
	Prod_Strategic_Offering STRING,
	Prod_Core_Class STRING,
	Prod_Sales_Rpt_Bus_Grp STRING,
	Prod_Sales_Rpt_Bus_Cat STRING,
	Prod_Sales_Rpt_Prod_Cat STRING, 
	Prod_Sales_Rpt_Cat STRING,
	Prod_Line_Cat STRING,
	Prod_Line_Bus_Cat STRING,
	Prod_LOB STRING,
	Prod_Line_Bus_Line STRING,
	Prod_Line_Features STRING,
	Prod_VSOE_Cat STRING,
	Prod_Version_Cat STRING,
	Prod_Tax_Cat STRING,
	Prod_License_Type STRING,
	Prod_Price_Type STRING,
	Prod_Pricing_Method STRING,
	Prod_Subscription_Pricing_Type STRING,
	Prod_Subscription_Type STRING,
	Prod_Cloud_Context STRING,
	Prod_Percent_of_Total_Include_Ind INT NOT NULL,
	Prod_Charge_Type STRING,
	Prod_Billing_Type STRING,
	Prod_SMB_Billing_Item_Num STRING,
	Prod_Enterprise_Billing_Item_Num STRING,
	Prod_Usage_Billing_Item_Num STRING,
	Prod_Billing_Role STRING,
	Prod_Bundle_Type STRING,
	Prod_Separate_Orders_Ind INT NOT NULL,
	Prod_HLE_Type STRING,
	Prod_HLE_Desc STRING,
	Prod_HLE_Value decimal(10,4),
	Prod_Svc_Product_Family STRING,
	Prod_Svc_Product_Line STRING,
	Prod_Svc_Product_Domain STRING,
	Prod_Svc_Product_Type STRING,
	Prod_License_Method_Value STRING,
	Prod_Status STRING,
	Prod_Item_Type STRING,
	Prod_Legacy_UOM STRING,
	Prod_Inv_Org STRING,
	Prod_Subinventory_Code STRING,
	Prod_Form_Product_Ind INT NOT NULL,
	Prod_Solution_Detail STRING,
	Prod_Line_Item_Cat STRING,
	Prod_Revenue_Product_Desc STRING,
	MDM_Record_State INT,
	ETL_Ins_Upd_Flag STRING
)
USING DELTA 
LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/Staging/{p_table_name}/{p_security_class}';


CREATE TABLE IF NOT EXISTS edw.{p_table_name} 
	(
		Product_Dim_Id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
		Rec_Process_Log_Id INT NOT NULL,
		Rec_Src_Application_Id INT NOT NULL,
		Rec_Src_Key STRING NOT NULL,
		Rec_Src_Create_Date TIMESTAMP,
		Rec_Src_Create_User STRING,
		Rec_Src_Update_Date TIMESTAMP,
		Rec_Src_Update_User STRING,
		Rec_EDW_Hash STRING,
		Rec_EDW_Create_Date TIMESTAMP NOT NULL,
		Rec_EDW_Update_Date TIMESTAMP NOT NULL,
		Rec_EDW_Effective_Start_Date TIMESTAMP NOT NULL,
		Rec_EDW_Effective_End_Date TIMESTAMP NOT NULL,
		Rec_EDW_Current_Ind INT NOT NULL,
		Prod_Name STRING,
		Prod_Legacy_Item_Num STRING,
		Prod_Legacy_Inventory_Item_Num STRING,
		Prod_Legacy_Org_Num STRING NOT NULL,
		Prod_Item_Num STRING, 
		Prod_Ext_ID STRING, 
		Prod_Cat STRING,
		Prod_Family STRING,
		Prod_Hosting_Component_Ind INT,
		Prod_PSA_Contract_Type STRING,
		Prod_Cus_Asset_Ind INT NOT NULL,
		Prod_Billing_Freq STRING,
		Prod_UOM STRING, 
		Prod_Active_Ind INT NOT NULL,
		Prod_Subinventory STRING,
		Prod_Solution STRING,
		Prod_Solution_Cat_1 STRING,
		Prod_Solution_Cat_2 STRING,
		Prod_Type STRING,
		Prod_Strategic_Offering STRING,
		Prod_Core_Class STRING,
		Prod_Sales_Rpt_Bus_Grp STRING,
		Prod_Sales_Rpt_Bus_Cat STRING,
		Prod_Sales_Rpt_Prod_Cat STRING,
		Prod_Sales_Rpt_Cat STRING,
		Prod_Line_Cat STRING,
		Prod_Line_Bus_Cat STRING,
		Prod_LOB STRING,
		Prod_Line_Bus_Line STRING,
		Prod_Line_Features STRING,
		Prod_VSOE_Cat STRING,
		Prod_Version_Cat STRING,
		Prod_Tax_Cat STRING,
		Prod_License_Type STRING,
		Prod_Price_Type STRING,
		Prod_Pricing_Method STRING,
		Prod_Subscription_Pricing_Type STRING,
		Prod_Subscription_Type STRING,
		Prod_Cloud_Context STRING,
		Prod_Percent_of_Total_Include_Ind INT NOT NULL,
		Prod_Charge_Type STRING,
		Prod_Billing_Type STRING,
		Prod_SMB_Billing_Item_Num STRING,
		Prod_Enterprise_Billing_Item_Num STRING,
		Prod_Usage_Billing_Item_Num STRING,
		Prod_Billing_Role STRING,
		Prod_Bundle_Type STRING,
		Prod_Separate_Orders_Ind INT NOT NULL,
		Prod_HLE_Type STRING,
		Prod_HLE_Desc STRING,
		Prod_HLE_Value decimal(10,4),
		Prod_Svc_Product_Family STRING,
		Prod_Svc_Product_Line STRING,
		Prod_Svc_Product_Domain STRING,
		Prod_Svc_Product_Type STRING,
		Prod_License_Method_Value STRING,
		Prod_Status STRING,
		Prod_Item_Type STRING,
		Prod_Legacy_UOM STRING,
		Prod_Inv_Org STRING,
		Prod_Subinventory_Code STRING,
		Prod_Form_Product_Ind INT NOT NULL,
		Prod_Solution_Detail STRING,
		Prod_Line_Item_Cat STRING,
		Prod_Revenue_Product_Desc STRING
		)
	USING DELTA
	LOCATION 'abfss://datalake@{p_storage_account_name}.dfs.core.windows.net/EDW/{p_table_name}/{p_security_class}';

